"""empty message

Revision ID: 01305bc4de1e
Revises: f26e0a3763c8
Create Date: 2023-06-22 09:43:46.514616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01305bc4de1e'
down_revision = 'f26e0a3763c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['name'])
    op.create_foreign_key(None, 'work_logging', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_logging', type_='foreignkey')
    op.drop_constraint(None, 'project', type_='unique')
    # ### end Alembic commands ###
